name: Docker Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: beakerandjake/listo-frontend

jobs:
  buildx:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
        
      - name: Build & Publish Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg FONT_AWESOME_NPM_AUTH_TOKEN=${{ secrets.FONT_AWESOME_NPM_AUTH_TOKEN }} \
            -t ${{ env.IMAGE_NAME }} \
            --push .        
